apiVersion: v1
kind: Pod
metadata:
  name: liveness
  labels:
    app: liveness
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/goproxy:0.1
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
